OLED_DRIVER = SSD1306      # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
#MOUSEKEY_ENABLE = yes
RGB_MATRIX_ENABLE = yes    # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
BACKLIGHT_DRIVER = software
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes      # Tap Dance
WS2812_DRIVER = vendor
